// react/src/components/Calendar.tsx
import type { Movie } from '../movies';
import { CalendarDoor } from './CalendarDoor';

type Props = { movies: Movie[]; availableDay: number; today: number | null; openedDays: number[]; openDay: number | null; onToggle: (day: number) => void };

export function Calendar({ movies, availableDay, today, openedDays, openDay, onToggle }: Props) {
  return <div className="calendar-grid">{movies.map(movie => (
    <CalendarDoor key={movie.day} movie={movie} locked={movie.day > availableDay}
      opened={openedDays.includes(movie.day)} isOpen={openDay === movie.day}
      isToday={today === movie.day} onToggle={onToggle}/>
  ))}</div>;
}

// angular/src/components/calendar.ts
import { Component, input, output } from '@angular/core';
import type { Movie } from '../movies';
import { CalendarDoor } from './calendar-door';

@Component({
  selector: 'app-calendar', standalone: true, imports: [CalendarDoor],
  template: `<div class="calendar-grid">
    @for (movie of movies(); track movie.day) {
      <app-calendar-door [movie]="movie" [locked]="movie.day > availableDay()"
        [opened]="openedDays().includes(movie.day)" [isOpen]="openDay() === movie.day"
        [isToday]="today() === movie.day" (toggle)="toggle.emit($event)"/>
    }
  </div>`,
})
export class Calendar {
  movies = input.required<Movie[]>();
  availableDay = input.required<number>();
  today = input.required<number | null>();
  openedDays = input.required<number[]>();
  openDay = input.required<number | null>();
  toggle = output<number>();
}
