// react/src/components/Countdown.tsx
import { daysUntilChristmas } from '../date';

export function Countdown({ date }: { date: Date }) {
  const days = daysUntilChristmas(date);
  return <div className="countdown"><span aria-hidden="true">✧</span>{days === 0
    ? <span>Merry Christmas!</span>
    : <span><strong>{days}</strong> {days === 1 ? 'day' : 'days'} until Christmas</span>}</div>;
}

// angular/src/components/countdown.ts
import { Component, computed, input } from '@angular/core';
import { daysUntilChristmas } from '../date';

@Component({
  selector: 'app-countdown', standalone: true,
  template: `<div class="countdown"><span aria-hidden="true">✧</span>
    @if (days() === 0) {<span>Merry Christmas!</span>}
    @else {<span><strong>{{ days() }}</strong> {{ days() === 1 ? 'day' : 'days' }} until Christmas</span>}
  </div>`,
})
export class Countdown {
  date = input.required<Date>();
  days = computed(() => daysUntilChristmas(this.date()));
}
