// vue/src/components/MovieEditor.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { Movie } from '../movies';
const props = defineProps<{ movies: Movie[]; saveError: string }>();
const emit = defineEmits<{ save: [movies: Movie[]]; cancel: [] }>();
const draft = ref(props.movies.map(movie => ({ ...movie })));
const error = ref('');

function submit() {
  if (draft.value.some(movie => !movie.title.trim())) {
    error.value = 'Please enter a movie title for every day.';
    return;
  }
  error.value = '';
  emit('save', draft.value.map(movie => ({ ...movie, title: movie.title.trim() })));
}
</script>

<template>
  <form class="movie-editor" aria-labelledby="editor-title" @submit.prevent="submit">
    <h2 id="editor-title">Choose your Christmas movies</h2>
    <p>This list reveals every surprise. Changes stay in this browser and can be saved until November 30.</p>
    <div class="editor-grid">
      <label v-for="movie in draft" :key="movie.day"><span>December {{ movie.day }}</span><input v-model="movie.title" type="text" required maxlength="120"/></label>
    </div>
    <p v-if="error || saveError" role="alert">{{ error || saveError }}</p>
    <div class="editor-actions"><button class="save-button" type="submit">Save movies</button><button class="secondary-button" type="button" @click="emit('cancel')">Cancel</button></div>
  </form>
</template>

// react/src/components/MovieEditor.tsx
import { useState, type FormEvent } from 'react';
import type { Movie } from '../movies';

type Props = { movies: Movie[]; onSave: (movies: Movie[]) => boolean; onCancel: () => void };

export function MovieEditor({ movies, onSave, onCancel }: Props) {
  const [draft, setDraft] = useState(() => movies.map(movie => ({ ...movie })));
  const [error, setError] = useState('');

  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (draft.some(movie => !movie.title.trim())) {
      setError('Please enter a movie title for every day.');
      return;
    }
    if (!onSave(draft.map(movie => ({ ...movie, title: movie.title.trim() })))) {
      setError('Your movies could not be saved. Check that browser storage is available and try again.');
    }
  }

  return <form className="movie-editor" onSubmit={submit} aria-labelledby="editor-title">
    <h2 id="editor-title">Choose your Christmas movies</h2>
    <p>This list reveals every surprise. Changes stay in this browser and can be saved until November 30.</p>
    <div className="editor-grid">{draft.map(movie => <label key={movie.day}>
      <span>December {movie.day}</span>
      <input type="text" required maxLength={120} value={movie.title}
        onChange={event => setDraft(current => current.map(item => item.day === movie.day ? { ...item, title: event.target.value } : item))}/>
    </label>)}</div>
    {error && <p role="alert">{error}</p>}
    <div className="editor-actions"><button className="save-button" type="submit">Save movies</button><button className="secondary-button" type="button" onClick={onCancel}>Cancel</button></div>
  </form>;
}
